#!/usr/bin/env bash

# This script is a wrapper for svlint/svls with a pre-configured ruleset.
# The ruleset should have the same suffix, and sit in `toml/`.
# To create a new ruleset, first create the TOML configuration, then
# hardlink this file like `ln wrapperTemplate bin/svlint-foo`.
# A hardlink, as opposed to a copy, means that edits to this script affect all
# rulesets - That's easier than editing lots of scripts.

THIS="${BASH_SOURCE[0]:-$0}"
BIN_DIR="$(dirname "${THIS}")"
TOML_DIR="$(dirname "${BIN_DIR}")/toml"
TOOL="$(basename "${THIS}" | tr "-" "\t" | cut -f1)"
RULESET="${TOML_DIR}/$(basename "${THIS}" | tr "-" "\t" | cut -f2).toml"
SVLINT_CONFIG="${RULESET}" ${TOOL} $*
